### ISSUE TITLE
battery status

### ISSUE THREAD

**Issue by JohanvanZanten** [denniedegroot/com.ring#15]
the battery status is not correctly (if any) shown

**Comment by denniedegroot** [comment]
Please give me a debug log from the athom-cli.

**Comment by JohanvanZanten** [comment]
Hi Dennie,

Where can I ifind the log file, I installed node.js and am able to login homey, but then it stops for me; not being a developer

**Comment by JohanvanZanten** [comment]
Hi Dennie,

Forgot to mention that the Ring is model Video Doorbell 2 which holds a battery; if you want to have me test this model please let me know

Grtx Johan van Zanten

**Comment by Genghes** [comment]
I have ‘Ring Doorbell 2’ and the battery never reports any Battery levels. Did not do it in v2.0.4 and not in the 2.1.0 Beta.

**Comment by Nakika** [comment]
Here ring doorbell 2. Battery status does not work either.

**Comment by Busta999** [comment]
Day 8 of Homey. I’m using a Standard Ring Doorbell and Beta 2.1.1 Ring App.

I can’t work out how to get the battery reporting to work.

Is this still a problem?

**Comment by nicofr1908** [comment]
Spam spamVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Busta999 <notifications@github.com> Datum: 04-05-19  12:24  (GMT+01:00) Aan: "denniedegroot/com.ring" <com.ring@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: Re: [denniedegroot/com.ring] battery status (#15) Day 8 of Homey. I’m using a Standard Ring Doorbell and Beta 2.1.1 Ring App.

I can’t work out how to get the battery reporting to work.

Is this still a problem?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/denniedegroot/com.ring/issues/15#issuecomment-489314700",

"url": "https://github.com/denniedegroot/com.ring/issues/15#issuecomment-489314700",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by denniedegroot** [comment]
@Busta999 can you send me a "Diagnostics report" for the Ring app from within the Homey app?

@nicofr1908 you are still subscribed to mails, please stop your nonsense and unsubscribe. And if you dont know how to do that contact github or read the manual.

**Comment by nicofr1908** [comment]
SpammmmmmmVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: denniedegroot <notifications@github.com> Datum: 04-05-19  13:22  (GMT+01:00) Aan: "denniedegroot/com.ring" <com.ring@noreply.github.com> Cc: nicofr1908 <nico@kloos.nu>, Mention <mention@noreply.github.com> Onderwerp: Re: [denniedegroot/com.ring] battery status (#15) @Busta999 can you send me a "Diagnostics report" for the Ring app from within the Homey app?
@nicofr1908 you are still subscribed to mails, please stop your nonsense and unsubscribe. And if you dont know how to do that contact github or read the manual.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/denniedegroot/com.ring/issues/15#issuecomment-489318297",
"url": "https://github.com/denniedegroot/com.ring/issues/15#issuecomment-489318297",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Busta999** [comment]
This is my Day 9 of Homey so hopefully this is what you need?

6feba58a-4455-4811-a3ce-af4f39ecfcaa

**Comment by denniedegroot** [comment]
@Busta999 Thank you, that is what I needed.

Can anybody test my bugfix/battery branch and test if the battery is now working correctly?

**Comment by Busta999** [comment]
Sorry, I have not yet worked out how to do that yet.

I found some instructions but they were for a PC 👎

**Comment by cbho** [comment]
Installed the battery-fix version - and battery status of my Ring Doorbell V1 was updated to the correct level ;-)

**Comment by denniedegroot** [comment]
@cbho Thanks for testing! I will upload a beta version of the app to the store.

**Comment by denniedegroot** [comment]
Pushed to stable. If the issue persists then please re-open this ticket.
