### ISSUE TITLE
Repeatedly the same image get sent from the image grabber

### ISSUE THREAD

**Issue by rodroz** [denniedegroot/com.ring#17]
Seems like there is no refresh in the ring doorbell for the snapshots. If I test, the same image is sent each time. Tried to add delay up to 7 seconds before grabbing with the flow card. 

If I go into the official ring app, the last image grabbed by the doorbell is updated in the ring app and then its that image that get grabbed by the Homey ring app.

**Comment by mruiter** [comment]
Strange i dont have this problem 

Verstuurd vanaf mijn iPhone

**Comment by rodroz** [comment]
That's really strange. Which version of ring do you have, I have the first v1 version. I deliberately have not gone into the official app since I wrote and have about 7 pictures in telegram with the same picture now after motion alarms.

**Comment by mruiter** [comment]
I have the ring pro 

Verstuurd vanaf mijn iPhone

**Comment by rodroz** [comment]
Maybe only issue with v1 ring then.

**Comment by denniedegroot** [comment]
That is weird indeed. The v1/v2 is a battery device right? Maybe it has to be 'woken' before it grabs a new image. But I currently don't know how to do this.

**Comment by rodroz** [comment]
Hi Dennie,

Mine v1 is hardwired and powered from steady source. Tested some more today and I can confirm it only grabs the last image that is updated when opening the official app.

**Comment by denniedegroot** [comment]
Could you try the beta branch? I made some adjustments so that it should refresh the image. (568c454)

**Comment by rodroz** [comment]
Hmm.. Think you are asking things I can't do unfortunately :-P.. I have no possibility to install on homey unless it's via the app store and I can't see any updates there yet.

**Comment by denniedegroot** [comment]
@mruiter could you maybe do a sanity check before I submit this to the app store?

**Comment by mruiter** [comment]
I should be landing in about 2 hours so I could do a check later today 

Verstuurd vanaf mijn iPhone

**Comment by nicofr1908** [comment]
Kunt u mij uit deze mailwisseing halen?Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Marco Ruiter <notifications@github.com> Datum: 10-03-19  16:35  (GMT+01:00) Aan: "denniedegroot/com.ring" <com.ring@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: Re: [denniedegroot/com.ring] Repeatedly the same image get sent from the image grabber (#17) I should be landing in about 2 hours so I could do a check later today 



Verstuurd vanaf mijn iPhone



> Op 10 mrt. 2019 om 16:16 heeft denniedegroot <notifications@github.com> het volgende geschreven:

> 

> @mruiter could you maybe do a sanity check before I submit this to the app store?

> 

> —

> You are receiving this because you were mentioned.

> Reply to this email directly, view it on GitHub, or mute the thread.





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/denniedegroot/com.ring","title":"denniedegroot/com.ring","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/denniedegroot/com.ring"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mruiter in #17: I should be landing in about 2 hours so I could do a check later today \n\nVerstuurd vanaf mijn iPhone\n\n\u003e Op 10 mrt. 2019 om 16:16 heeft denniedegroot \u003cnotifications@github.com\u003e het volgende geschreven:\n\u003e \n\u003e @mruiter could you maybe do a sanity check before I submit this to the app store?\n\u003e \n\u003e —\n\u003e You are receiving this because you were mentioned.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n"}],"action":{"name":"View Issue","url":"https://github.com/denniedegroot/com.ring/issues/17#issuecomment-471316698"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/denniedegroot/com.ring/issues/17#issuecomment-471316698",

"url": "https://github.com/denniedegroot/com.ring/issues/17#issuecomment-471316698",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by mruiter** [comment]
Dat zul je zelf op github moeten doen.
Maar kijk even verder en onder aan de mail zie je een mute knop

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
Dennie ik heb nu een dag de nieuwe beta versie getest en alles lijkt goed te functioneren 

Verstuurd vanaf mijn iPhone

**Comment by denniedegroot** [comment]
It seems that it is no longer working. Ring has blocked the api, other apps are reporting the same error.
I will investigate this further in #10 .
