### ISSUE TITLE
Two factor authentication support

### ISSUE THREAD

**Issue by Peanudt** [denniedegroot/com.ring#31]
With the two factor authentication for ring activated, I cannot authorize Homey. Set-up in the app only allows username/password combo.

**Comment by jasoncheesemanuk** [comment]
About 3,500 passwords have been released onto the DarkWeb so w have been advised to use Two Factor Authentication now. If you don’t support it, we are going to be a bit stuck!

**Comment by mruiter** [comment]
Again those passwords are reused passwords from other websites that got hacked. It’s time that people learn to use unique passwords for their private stuff , nothing will solve the stupid people problem not even triple factor authentication 

Just choose a unique password and keep mfa disabled. 

If ring ever gets hacked mfa doesn’t matter since the hackers also have access to those tokens then.

**Comment by mruiter** [comment]
Again those passwords are reused passwords from other websites that got hacked. It’s time that people learn to use unique passwords for their private stuff , nothing will solve the stupid people problem not even triple factor authentication 

Verstuurd vanaf mijn iPhone

**Comment by jasoncheesemanuk** [comment]
Mine wasn’t a re-used password and it was also pretty complicated (numbers, letters, other characters). 

I didn’t know that Ring doesn’t allow other apps to interface with it. I will use a motion sensor by the door rather than using the Ring one.

Thanks
