### ISSUE TITLE
Ring door sensor not supported. 

### ISSUE THREAD

**Issue by kapusticka** [denniedegroot/com.ring#8]
Hi. Can you add supper for Ring door sensor?

**Comment by mruiter** [comment]
The ring security system isn’t open protocol and it’s even more secure then ring doorbell .
It’s in rings interested not to be used by others since they are a certified on a level as a security system .

The ring doorbell isn’t open protocol either but was hacked / reversed engineered. 

But maybee Dennie has different info 

Verstuurd vanaf mijn iPhone

**Comment by denniedegroot** [comment]
What Marco says is true. I dont think it will be possible soon or ever.
